[[pages]]
path = "main.py"
name = "main"
icon = "ğŸ "

[[pages]]
path = "proyecto/paginas/eventos.py"
name = "Eventos"
icon = "ğŸ­"

[[pages]]
path = "proyecto/paginas/restaurantes.py"
name = "Restaurantes"
icon = "ğŸ½ï¸"

[[pages]]
path = "proyecto/paginas/mapas.py"
name = "Mapas"
icon = "ğŸŒ"

