[[pages]]
path = "main.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "paginas/eventos.py"
name = "Eventos"
icon = "ğŸ­"

[[pages]]
path = "paginas/restaurantes.py"
name = "Restaurantes"
icon = "ğŸ½ï¸"

[[pages]]
path = "paginas/mapas.py"
name = "Mapas"
icon = "ğŸŒ"